INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Pc Gamer', 'Processador Ryzen 5 5600GT, Placa Gráfica Radeon Graphics Vega 7, 16GB RAM, SSD 240GB, Gabinete RGB', 2.137, 15, 'Informatica')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Fritadeira', 'Sem Óleo Oster 127V - OFRT520, PRETO', 219, 10, 'Eletroportateis')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Apple iPhone 13', '(128 GB) - Luz das estrelas', 2.815, 5, 'Celulares')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Monitor Gamer', 'Alienware 27 QHD - AW2725DM', 2.229, 2, 'Informatica')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Parafusadeira', 'GSR 1000 Smart, Com Acessórios, 12 Volts', 249, 15, 'Ferramentas')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Capa de Chuva', 'EVA Adulto Unisex c/Capuz Impermeável', 22, 15, 'Moda')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Maybelline', 'NY Instant Age Rewind Corretivo Líquido', 52, 15, 'Beleza')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Essencialismo', 'A disciplinada busca por menos', 20, 15, 'Livros')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Basta Sentir', 'Transformação, perdas, oportunidades ecrescimento', 20, 15, 'Livros')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Ed & Lorraine Warren', 'Vidas Eternas - O livro que deu origem ao filme Invocação do Mal: O Último Ritual: 3', 20, 15, 'Livros')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Um verão radiante', 'Literatura Mundial e Ficção', 20, 15, 'Livros')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Conjunto de pinças profissionais', 'Pinças de aço inoxidável para sobrancelhas', 12, 5, 'Marcas')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Chave catraca', '7 mm, chave de catraca combinada, 72 dentes, aço cromo vanádio', 21, 10, 'Ferramentas')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Garrafa', 'Garrafa térmica Classic Stanley', 181, 2, 'Cozinha')
INSERT INTO tb_product(name, description, price, stock, category) VALUES ('Mixer Power Inox', 'Mixer Power Inox 3 em 1 600W Elgin Lunar 110V - Mixer, triturador e batedor', 137, 10, 'Cozinha')

